// Every user visible name for the "Someday" list lives here, so a rename is one edit.
export const SOMEDAY = {
  name: "Someday",
  page: "/someday",
  heading: "someday.",
  intro: "Here, you can curate all the hoshigos that you would like to enjoy someday too. A list for your future self.",
  addLead: "Add to your someday by browsing other profiles or ",
  addPress: "Press here",
  doneWith: "Done with this",
  addNote: "Add a note",
  notePlaceholder: "Who gave you the tip, or why it caught your eye",
  notePublicPlaceholder: "Visible to anyone who can see your someday list",
  noteLabel: "A note for yourself",
  savedAddNote: "Add a note?",
  dialogTitle: "Save for someday",
  saving: "Saving…",
  saveFailed: "That didn’t save. Try again in a moment.",
  save: "Save for someday",
  saved: "Saved for someday",
  lovedIt: "Loved it",
  notOne: "Not a hoshigo",
  confirmRemove: "Yes, remove it from my someday list",
  keep: "Cancel",
  empty: "Nothing saved yet. When a friend's hoshigo looks like something for you, save it for someday and it waits here.",
  alsoFor: "Also a hoshigo for",
  fromWord: "from",
  savedOn: (date: string) => `saved ${date}`,
  settingsLabel: "Who can see your someday list?",
  onlyMe: "Only me",
  onPage: "Visible on my page",
  onPageHint: "People who can see your page can see what you saved for someday.",
  onlyMeHint: "Only you see what you saved for someday.",
  profileLink: (name: string) => `${name}’s someday list`,
  othersHeading: (name: string) => `${name}’s someday.`,
} as const;
